dic = {
    "Filme": [
        "A BELA E A FERA",
        "A ORIGEM",
        "ALADDIN",
        "AVATAR",
        "BARBIE",
        "BATMAN",
        "CORALINE",
        "DIVERTIDAMENTE",
        "ENCANTO",
        "FROZEN",
        "HARRY POTTER",
        "HOMEM-ARANHA",
        "HOMEM-FORMIGA",
        "JURASSIC PARK",
        "MADAGASCAR",
        "MEU MALVADO FAVORITO",
        "O REI LEÃO",
        "O SENHOR DOS ANÉIS",
        "OS INCRÍVEIS",
        "PIRATAS DO CARIBE",
        "PLANETA DOS MACACOS",
        "SHREK",
        "STAR WARS",
        "TITANIC",
        "TOY STORY",
        "TRANFORMERS",   
        "VELÓZES E FURIOSOS",
        "VIDA DE INSETO"
    ],
    "Fruta": [
        "ABACATE",
        "ABACAXI",
        "AMORA",
        "BANANA",
        "CAJU",
        "CARAMBOLA",
        "COCO",
        "CUPUAÇU",
        "FIGO",
        "FRAMBOESA",
        "GOIABA",
        "GRAVIOLA",
        "JABUTICABA",
        "JACA",
        "KIWI",
        "LARANJA",
        "MANGA",
        "MELANCIA",
        "MELÃO",
        "MORANGO",
        "MURTA",
        "MURICI",
        "NECTARINA",
        "PÊRA",
        "PITANGA",
        "TAMARINDO",
        "TANJA",
        "UVA"
    ],
    "Lugar": [
        "AXIXÁ",
        "BRASÍLIA",
        "CAMPINAS",
        "CURITIBA",
        "FLORIANÓPOLIS",
        "FORTALEZA",
        "JOÃO PESSOA",
        "LAGO DAS PEDRAS",
        "MANAUS",
        "NATAL",
        "PORTO ALEGRE",
        "RECIFE",
        "RIO DE JANEIRO",
        "ROSÁRIO",
        "SALVADOR",
        "SANTA INÊS",
        "SANTA LUZIA",
        "SÃO PAULO"
    ],
    "Animal": [
        "ARARA",
        "CACHORRO",
        "CAMELO",
        "CAVALO",
        "COBRA",
        "ELEFANTE",
        "FALCÃO",
        "GALO",
        "GATO",
        "GIRAFA",
        "GORILA",
        "JACARÉ",
        "LEÃO",
        "LOBO",
        "ORNITORRINCO",
        "PANDA",
        "PAPAGAIO",
        "PORCO-ESPINHO",
        "RAPOSA",
        "TAMANDUÁ",
        "TIGRE",
        "TARTARUGA"
    ],
    "Objeto": [
        "ASPIRADOR",
        "BICICLETA",
        "BOLA",
        "CAMPO",
        "CADEIRA",
        "CADERNO",
        "CANETA",
        "CELULAR",
        "CERVEJA",
        "CHAVE",
        "COPO",
        "COMPUTADOR",
        "ESCOVA",
        "ESPELHO",
        "FONE DE OUVIDO",
        "GELADEIRA",
        "GUITARRA",
        "LIVRO",
        "MESA",
        "MICRO-ONDAS",
        "MOCHILA",
        "PANELA",
        "RELÓGIO",
        "TESOURA",
        "TELEVISÃO",
        "TRAVESSEIRO"
    ],
    "Profissão": [
        "ADVOGADO",
        "ARQUITETO",
        "BARBEIRO",
        "BANCÁRIO",
        "BOMBEIRO",
        "CANTOR",
        "CARPINTEIRO",
        "COSTUREIRA",
        "COZINHEIRO",
        "DENTISTA",
        "DJ",
        "ELETRICISTA",
        "ENGENHEIRO",
        "JORNALISTA",
        "MÉDICO",
        "MOTORISTA",
        "PADEIRO",
        "PILOTO",
        "PINTOR",
        "PROFESSOR",
        "PROGRAMADOR",
        "PSICÓLOGO",
        "VETERINÁRIO",
        "YOUTUBER"
    ],
    "Time de Futebol": [
        "ATLÉTICO MINEIRO",
        "ATLÉTICO PARANAENSE",
        "BAHIA",
        "BOTAFOGO",
        "CORINTHIANS",
        "CRUZEIRO",
        "CUIABÁ",
        "FLAMENGO",
        "FLUMINENSE",
        "FORTALEZA",
        "GOIÁS",
        "GRÊMIO",
        "INTERNACIONAL",
        "PALMEIRAS",
        "SANTOS",
        "SPORT",
        "VASCO"
    ],
    "País": [
        "ÁFRICA DO SUL",
        "ALEMANHA",
        "ARGENTINA",
        "AUSTRÁLIA",
        "BRASIL",
        "CANADÁ",
        "CHILE",
        "CHINA",
        "COREIA DO SUL",
        "EUA",
        "EGITO",
        "ESPANHA",
        "ESTADOS UNIDOS",
        "FRANÇA",
        "ÍNDIA",
        "INGLATERRA",
        "ITÁLIA",
        "JAPÃO",
        "MÉXICO",
        "NORUEGA",
        "PORTUGAL",
        "RÚSSIA",
        "SUÉCIA",
        "UCRÂNIA"
    ],
    "Cor": [
        "AMARELO",
        "ANIL",
        "AZUL",
        "BEGE",
        "BRANCO",
        "CARMESIM",
        "CINZA",
        "DOURADO",
        "LARANJA",
        "MARROM",
        "PRATA",
        "PRETO",
        "ROSA",
        "ROXO",
        "SALMÃO",
        "TURQUESA",
        "VERDE",
        "VERMELHO",
        "VIOLETA"
    ],
    "Personagem": [
        "ASH KETCHUM",
        "BATMAN",
        "BOB ESPONJA",
        "DARTH VADER",
        "DONALD",
        "GOKU",
        "HARRY POTTER",
        "HOMEM-ARANHA",
        "HOMER SIMPSON",
        "KRATOS",
        "LARA CROFT",
        "LINK",
        "LUIGI",
        "MARIO",
        "MEGAMAN",
        "MICKEY MOUSE",
        "MINNIE",
        "NARUTO",
        "PATRICK ESTRELA",
        "SCOOBY-DOO",
        "SHERLOCK HOLMES",
        "SONIC",
        "SUPERMAN",
        "YODA"
    ],
    "Marca": [
        "ADIDAS",
        "AMAZON",
        "APPLE",
        "BMW",
        "COCA-COLA",
        "FORD",
        "GOOGLE",
        "HONDA",
        "INTEL",
        "MERCEDES",
        "MICROSOFT",
        "NIKE",
        "PEPSI",
        "SONY",
        "SAMSUNG"
    ],
    "Comida": [
        "ACARAJÉ",
        "AÇAÍ",
        "ARROZ",
        "BRIGADEIRO",
        "CHURRASCO",
        "FEIJOADA",
        "HAMBÚRGUER",
        "LASANHA",
        "MACARRÃO",
        "MOQUECA",
        "PÃO",
        "PAMONHA",
        "PIZZA",
        "RABADA",
        "SALADA",
        "SORVETE",
        "SUSHI",
        "TACOS"
    ],
    "Instrumento Musical": [
        "ACORDEON",
        "CELLO",
        "CONTRABAIXO",
        "FLAUTA",
        "PIANO",
        "SAXOFONE",
        "TAMBOR",
        "TROMPETE",
        "VIOLÃO",
        "VIOLINO"
    ],
    "Esporte": [
        "BASQUETE",
        "BOXE",
        "CICLISMO",
        "CORRIDA",
        "FUTEBOL",
        "GINÁSTICA",
        "NATAÇÃO",
        "SURFE",
        "TÊNIS",
        "VÔLEI"
    ],
    "Bebida": [
        "ÁGUA",
        "CACHAÇA",
        "CAFÉ",
        "CHÁ",
        "CERVEJA",
        "LEITE",
        "REFRIGERANTE",
        "SUCO",
        "VINHO",
        "WHISKY"
    ],
    "Meio de Transporte": [
        "AVIÃO",
        "BARCO",
        "BICICLETA",
        "CAMINHÃO",
        "CARRO",
        "METRÔ",
        "MOTO",
        "ÔNIBUS",
        "SKATE",
        "TREM"
    ],
    "Peça de Roupa": [
        "BLUSA",
        "CAMISA",
        "CALÇA",
        "CASACO",
        "MEIA",
        "SAPATO",
        "SAIA",
        "TÊNIS",
        "VESTIDO"
    ],
    "Doença": [
        "ALZHEIMER",
        "ASMA",
        "CÂNCER",
        "COVID",
        "DIABETES",
        "DENGUE",
        "GRIPE",
        "HIPERTENSÃO",
        "PARKINSON",
        "RESFRIADO"
    ],
    "Lugar": [
        "AXIXÁ",
        "BRASÍLIA",
        "CAMPINAS",
        "CURITIBA",
        "FLORIANÓPOLIS",
        "FORTALEZA",
        "JOÃO PESSOA",
        "LAGO DAS PEDRAS",
        "MANAUS",
        "NATAL",
        "PORTO ALEGRE",
        "RECIFE",
        "RIO DE JANEIRO",
        "ROSÁRIO",
        "SALVADOR",
        "SANTA INÊS",
        "SANTA LUZIA",
        "SÃO PAULO"
    ],
    "Planta": [
        "ALECRIM",
        "BAMBU",
        "CACTO",
        "DENTE-DE-LEÃO",
        "ESPADA-DE-SÃO-JORGE",
        "GIRASSOL",
        "HIBISCO",
        "HORTELÃ",
        "JASMIM",
        "LAVANDA",
        "LÍRIO",
        "MANJERICÃO",
        "ORQUÍDEA",
        "ROSA",
        "SAMAMBAIA"
    ],
    "Programa de TV": [
        "BIG BROTHER",
        "BREAKING BAD",
        "CHAVES",
        "F.R.I.E.N.D.S",
        "GREY'S ANATOMY",
        "OS SIMPSONS",
        "STRANGER THINGS",
        "THE OFFICE",
        "TODO MUNDO ODEIA O CHRIS",
        "VIKINGS"
    ],
    "Jogo": [
        "BATALHA NAVAL",
        "BANCO IMOBILIÁRIO",
        "CARA A CARA",
        "DAMAS",
        "IMAGEM E AÇÃO",
        "JOGO DA VIDA",
        "PIQUE-ESCONDE",
        "STOP",
        "UNO",
        "XADREZ"
    ],
    "Tecnologia": [
        "COMPUTADOR",
        "IMPRESSORA",
        "INTERNET",
        "MEMÓRIA RAM",
        "MONITOR",
        "PROCESSADOR",
        "ROTEADOR",
        "SMARTPHONE",
        "TABLET",
        "WI-FI"
    ],
    "Matéria Escolar": [
        "BIOLOGIA",
        "CIÊNCIAS",
        "EDUCAÇÃO FÍSICA",
        "FILOSOFIA",
        "FÍSICA",
        "GEOGRAFIA",
        "HISTÓRIA",
        "MATEMÁTICA",
        "PORTUGUÊS",
        "QUÍMICA"
    ]
}
