dic = {
    "Filme": [
        "HOMEM ARANHA", "STAR WARS", "MEU MALVADO FAVORITO", "HOMEM FORMIGA", "SHREK",
        "TOY STORY", "TITANIC", "VELOZES E FURIOSOS", "O REI LEAO", "MADAGASCAR",
        "JURASSIC PARK", "OS INCRIVEIS", "FROZEN", "ALADDIN", "BATMAN",
        "SUPERMAN", "A BELA E A FERA", "PIRATAS DO CARIBE", "AVATAR", "PLANETA DOS MACACOS"
    ],
    "Fruta": [
        "UVA", "TANJA", "GOIABA", "MURTA", "MURICI", "ABACATE", "AMOROSA",
        "BANANA", "MANGA", "MORANGO", "LARANJA", "CAJU", "MARACUJA",
        "ABACAXI", "COCO", "PITANGA", "JABUTICABA", "PERA", "MELANCIA",
        "KIWI", "MELAO", "TAMARINDO", "FRAMBOESA"
    ],
    "Lugar": [
        "LAGO DAS PEDRAS", "AXIXA", "SANTA LUZIA", "SANTA INES", "ROSARIO",
        "RIO DE JANEIRO", "SAO PAULO", "BELO HORIZONTE", "FORTALEZA", "RECIFE",
        "SALVADOR", "PORTO ALEGRE", "MANAUS", "BRASILIA", "CURITIBA",
        "CAMPINAS", "NATAL", "GOIANIA", "JOAO PESSOA", "FLORIANOPOLIS"
    ],
    "Animal": [
        "CACHORRO", "GATO", "ELEFANTE", "GIRAFA", "LEAO",
        "TIGRE", "COBRA", "TARTARUGA", "PAPAGAIO", "LOBO",
        "JACARE", "ARARA", "GORILA", "ORNITORRINCO", "CAVALO",
        "RINOCERONTE", "GALO", "TAMANDUA", "PANDA", "FALCAO"
    ],
    "Objeto": [
        "CADEIRA", "MESA", "COMPUTADOR", "CELULAR", "GELADEIRA",
        "TELEVISAO", "LIVRO", "CADERNO", "CANETA", "LAMPADA",
        "TESOURA", "RELOGIO", "MOCHILA", "FONE DE OUVIDO", "CHAVE",
        "GUITARRA", "ASPIRADOR", "BICICLETA", "PANELA", "MICROONDAS"
    ],
    "Profissão": [
        "MEDICO", "PROFESSOR", "ENGENHEIRO", "CANTOR", "ADVOGADO",
        "JORNALISTA", "ARQUITETO", "VETERINARIO", "PILOTO", "BOMBEIRO",
        "POLICIAL", "DENTISTA", "PSICOLOGO", "COSTUREIRA", "MOTORISTA",
        "BARBEIRO", "ELETRICISTA", "PINTOR", "PROGRAMADOR", "ATOR"
    ],
    "Time de Futebol": [
        "FLAMENGO", "CORINTHIANS", "SAO PAULO", "PALMEIRAS", "VASCO",
        "SANTOS", "INTERNACIONAL", "GREMIO", "FLUMINENSE", "CRUZEIRO",
        "ATLETICO MINEIRO", "BAHIA", "FORTALEZA", "BOTAFOGO", "SPORT",
        "GOIAS", "CUIABA", "ATLETICO PARANAENSE", "CHAPECOENSE", "CEARA"
    ],
    "País": [
        "BRASIL", "ARGENTINA", "EUA", "ALEMANHA", "FRANCA",
        "ITALIA", "JAPAO", "CHINA", "ESPANHA", "PORTUGAL",
        "CANADA", "MEXICO", "INGLATERRA", "AUSTRALIA", "RUSSIA",
        "INDIA", "AFRICA DO SUL", "COREIA DO SUL", "CHILE", "PERU"
    ],
    "Cor": [
        "VERMELHO", "AZUL", "VERDE", "AMARELO", "PRETO",
        "BRANCO", "LARANJA", "ROXO", "CINZA", "MARROM",
        "ROSA", "BEGE", "VIOLETA", "TURQUESA", "DOURADO",
        "PRATA", "BORDO", "SALMAO", "ANIL", "CARMESIM"
    ],
    "Personagem": [
        "MICKEY MOUSE", "HARRY POTTER", "BATMAN", "SUPERMAN", "HOMEM ARANHA",
        "HOMER SIMPSON", "GOKU", "NARUTO", "SONIC", "MARIO",
        "LUIGI", "SCOOBY DOO", "PATRICK ESTRELA", "BOB ESPONJA", "SHERLOCK HOLMES",
        "DARTH VADER", "YODA", "LARA CROFT", "KRATOS", "MEGAMAN"
    ]
}
